### ISSUE TITLE
フロント側でトークンを取得する

### ISSUE THREAD

**Issue by Matsumoto-mm12** [TO053037/SlackCloneApp#41]

**Comment by TO053037** [comment]
これpull requestと間違えてます？？

**Comment by Matsumoto-mm12** [comment]
いや、間違えてないです！
普段issueと紐づけてブランチを作ってるんですけど、普通に作ったほうがいいですかね？

**Comment by TO053037** [comment]
> いや、間違えてないです！ 普段issueと紐づけてブランチを作ってるんですけど、普通に作ったほうがいいですかね？

そんな手法があるんですね！
知らなかったです。

確かに、解決すべき課題が明確になっていいかもしれないですね！
