### ISSUE TITLE
リダイレクト設定

### ISSUE THREAD

**Issue by Matsumoto-mm12** [TO053037/SlackCloneApp#85]
workspace一覧が取得できず、エラーがでる
リロードすればエラーは消える（Tokenがセットされるので）
→　ログイン状態に応じてリダイレクトされるようにする

**Comment by Matsumoto-mm12** [comment]
応急処置として、トークンが保存されていないときはgetTokenを呼べないようにしたが
これだと
ログイン→リロード→認証が必要な作業（例えばワークスペース一覧を取得するなど）
のようにする必要がある
理想はログイン後に例えばワークスペース一覧取得まで自動的に行う状態

リロードしないとログインしてもTokenが設定されていない状態のままなのをなんとかしたい

**Comment by Matsumoto-mm12** [comment]
調べてみたんですが、Cookieをセットしてそれを利用したい場合、やりとりを分ける必要があるみたいです。getTokenはcookieからtokenを取り出すんですが、ログインボタンを押したときに、返ってきたtokenをcookieにセットするのと、cookieからtokenを取り出すっていうのを同時にやろうとしてたのがよくなかったというか、それはそもそも無理なことだったぽいです。

**Comment by Matsumoto-mm12** [comment]
なのでログインとトークンを利用した処理はそれぞれイベントを分けるやり方で合ってるみたいです。

**Comment by Matsumoto-mm12** [comment]
> ログイン→リロード→認証が必要な作業（例えばワークスペース一覧を取得するなど）
> のようにする必要がある

これに関してはリロードしなくてもイベントを分けることで解決しました

**Comment by TO053037** [comment]
> 
> > ログイン→リロード→認証が必要な作業（例えばワークスペース一覧を取得するなど）
> > のようにする必要がある
> 
> これに関してはリロードしなくてもイベントを分けることで解決しました
> 
> 
> 

そうですね！
処理ごとにコンポーネントを作って組み合わせるのが良いと思います。
